name: CI

on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build CI image
        run: docker build -t ros2-perception-sim-ci .

      - name: Colcon test
        run: |
          docker run --rm ros2-perception-sim-ci bash -c "
          source /opt/ros/jazzy/setup.bash
          source install/setup.bash
          colcon test --packages-select fake_sensors || true
          colcon test-result --verbose
          "