name: CI

on: push

jobs:
  basic_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: ROS2 Setup
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy 

      - name: Colcon build and test
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --packages-select fake_sensors
          colcon test --packages-select fake_sensors
